### ISSUE TITLE
All entities become unavailable when R2 is in sleep mode

### ISSUE THREAD

**Issue by alsFC** [JackJPowell/hass-unfoldedcircle#1]
I'm really happy to test communication from within HA with the R2. Thank you for developing this integration!

The following issue I can report: When the R2 goes to sleep mode the entities are unavailable in Home Assistant. Not sure if that has to be fixed by UC e.g. by routing API requests over the dock instead of the remote.

**Comment by JackJPowell** [comment]
Currently, only the remote is able to field these requests. The devs have addressed this concern in the discord and have stated while they do see the issue, they have no plans to adjust their interaction model. This may change with time but for now when the remote is asleep communication halts.
