### ISSUE TITLE
Zeroconf

### ISSUE THREAD

**Issue by TrialMaster** [JackJPowell/hass-unfoldedcircle#10]
### Discussed in https://github.com/JackJPowell/hass-unfoldedcircle/discussions/9

<div type='discussions-op-text'>

<sup>Originally posted by **TrialMaster** December 30, 2023</sup>
Hello, I have this integration set up but keep receiving discovery prompts even though I have ignored previously. I have several instances of the integration sitting in HA. I have tried toggling off “Enable newly added entities.” in HA and will see if that stops the discoveries. I should add I have deleted all the discovered instances that have not been setup. </div>

**Comment by JackJPowell** [comment]
Hi Trialmaster,

Sorry you're having trouble. Can you think of anything different about your setup? Do you have more than one remote? I don't believe these should matter but did you rename your remote or is its IP address changing frequently? 

Ultimately, I need to take a look at the zeroconf broadcast data and by checking what is there, we can narrow down what might be changing in your setup that is causing home assistant to see your device as new over and over again.

**Comment by TrialMaster** [comment]
Hi Jack

Sorry for delay, I’ve been overseas. 

My setup is pretty stock standard. I have fixed address for R2 & Dock in my router and only the one remote. I haven’t renamed the remote or the dock. 

Happy to provide anything you request, it’s a strange on I can go weeks without the issue and then today it found the remote twice?

**Comment by JackJPowell** [comment]
No problem at all. I’m hopeful the next release which should be out later
today will address the issue. It’s a big one that also includes some
improvements to zeroconf as well. Keep me updated after the next release
comes out.

**Comment by JackJPowell** [comment]
Closing this issue. If you are still having trouble, join us over in #23 where we are working through a similar problem. Thanks @TrialMaster
