### ISSUE TITLE
Feature Request, control display brightness 

### ISSUE THREAD

**Issue by Dodoooh** [JackJPowell/hass-unfoldedcircle#14]
hello thank you very much for your work

I would like to control the display brightness also deactivating the automatic brightness adjustment via Home Assistant, e.g. reduce it to a minimum when watching a movie.

**Comment by JackJPowell** [comment]
Hey Do,

I like this idea! I'll aim to have it done this weekend.

**Comment by JackJPowell** [comment]
Hi @Dodoooh,

So much for that weekend but v0.6.0 adds full unfolded circle configuration setting support along with a ton of other new additions. Hope you find it useful!

#20
