### ISSUE TITLE
New Activities not showing in the integration

### ISSUE THREAD

**Issue by schildgenb** [JackJPowell/hass-unfoldedcircle#15]
I added some more activities to the remote but they are not showing up in the integration. I have removed the integration and re-added it but still the same ones show up. I even deleted the custom integration and re-installed it but still the same ones are there and non of the new ones.

**Comment by JackJPowell** [comment]
Sorry you're having trouble. Do you happen to have more than 10 activities? There is a known limitation that only pulls back your first ten. I'm planning some updates this weekend. If this happens to be your problem, I'll try and get it patched in too.

**Comment by schildgenb** [comment]
I bet that is the issue and it's okay I just added them recently and noticed.

**Comment by JackJPowell** [comment]
I just pushed an update that increases the activity limit to 100. Give it a shot and let me know how it goes.

**Comment by schildgenb** [comment]
I just tried it today. Eben un-installed and reinstalled but it still only pulled in the same ones and not the new ones I created.

**Comment by JackJPowell** [comment]
Well that is frustrating. 
Here is what I tried. 
- Before correcting the issue I created 11 new 'test' activities on the remote. 
- I did a reload and it pulled in test 1-8 since I already had some normal activities defined. 
- I applied the fix and rebooted HA for it to take effect (did you reboot? Probably, but had to ask)
- I checked again and had all 11 test + 2 normal activities in HA. 


Quick check
- in hacs, you have 0.3.1 installed?

**Comment by schildgenb** [comment]
So I got it working. I uninstalled and the rebooted to be sure. Then I reinstalled it from Hacs made just that the latest version was selected. Then I went to the files and reviewed the Manifest.json with the one installed on mine compared it to the github one. Noticed they were not the same so not sure why it downloaded wrong. I just downloaded it manually and then replaced the files and that worked. It is now pulling in all the entities!

**Comment by JackJPowell** [comment]
Yep. Not sure how I did it, but I managed to zip up the wrong version of manifest.json
I've updated the release so a redownload or any new download will be good going forward. I'll have a new release with new additions shortly. Thanks for helping me pinpoint the issue
