### ISSUE TITLE
Integration not changing activities inside activity group + question on PIN-authentication

### ISSUE THREAD

**Issue by RC-Thoughts** [JackJPowell/hass-unfoldedcircle#22]
After latest update to v.0.6.0 I'm unable to change activities from drop-down control. All my activities are inside activity group so old switches are not working anymore.

**Version info**
HA 2024.3.0
Supervisor 2024.02.1
HACS 1.34.0
Python 3.12.2

**To Reproduce**
1. Go to device
2. Select another activity from drop-down list

**Expected behavior**
Remote Two should change to selected new activity

** Question**
After every restart of HA a new remote two device is found asking for PIN, is this expected behavior?

**Screenshots**
![image](https://github.com/JackJPowell/hass-unfoldedcircle/assets/18365352/3b380d1c-3dc6-41c8-a10f-463da6c6563d)

**Comment by RC-Thoughts** [comment]
> Now, are you saying that when you select a new activity from the dropdown, the above isn't happening?

No, it does not.

In the 0.3.x version we had switches to start and stop activities. In 0.6.0 selecting a activity from drop-down should to my understanding start that activity, this does not happen. So currently in 0.6.0 I have no way to control R2 from HA.

And logs are filled with lines:
`2024-03-08 13:10:29.770675 +00:00	core	ERROR	Error encountered while processing the incoming HTTP request: AuthError("Authentication error")`

Regarding the ignore reconfig, if I ignore the discovered integration and restart HA the integrations does not work since I get a message "Integration requires reconfiguration" with error "Failed to set up" and as mouseover "could not authenticate". So I need to reconfigure the integration ie need to give the pin-code again.  I have only one ignored unfolded-integration in my ignored-list.

**Comment by RC-Thoughts** [comment]
And here's the authentication-issue (repeating loglines) from HA logs:

`2024-03-08 15:22:20.719 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/pyUnfoldedCircleRemote/remote.py", line 1264, in update_data
    data = await self._remote.get_entity_data(self._id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyUnfoldedCircleRemote/remote.py", line 1155, in get_entity_data
    await self.raise_on_error(response)
  File "/usr/local/lib/python3.12/site-packages/pyUnfoldedCircleRemote/remote.py", line 416, in raise_on_error
    raise HTTPError(response.status, msg)
pyUnfoldedCircleRemote.remote.HTTPError: ('401 Request: NOT_AUTHORIZED Reason: Authentication error', 401)`

**Comment by RC-Thoughts** [comment]
Ok, more testing and diagnosing done, I think we know now what happens.

If you have 0.3.0 installed and update to 0.6.0 you end up with two devices under the integration, one with 1 entity and one with 24 entities. Going to any of those will show the 24 entities, you also have integration finding remote after every reboot and drop-down starting of activities does not work due authentication issue.

If you remove the integration and re-install you end up in same situation with two devices and this is where the authentication-issues occur.

Instead, you need to remove the devices from integration, then reinstall the integration. Now you get asked about the host and pin, and after that both issues are resolved. No more faulty discoveries and also the drop-down start of activities work.

Maybe the update process could use some tuning?

As an issue this is now solved.

**Comment by JackJPowell** [comment]
Thanks for the extra diagnosis and I'm glad you have it working! I definitely tested the upgrade path from .3.0 but I'll reinstall it and try again. Looks like I missed something. 

Any chance you have the ID of the lone entity in the other device? Or just remember what type it was?

**Comment by RC-Thoughts** [comment]
Unfortunately no ID since I cant see it anywhere anymore. The type was the same as the present one.  
About the update, I did the update from HACS, you maybe did it differently?

**Comment by JackJPowell** [comment]
It was a great thought, but not quite it. 

1. Delete current integration and redownload 0.3.1 from HACS
2. Restart Home Assistant and add back Unfolded Circle Remote (13 Entities as expected)
3. Upgrade via HACS and restart HA
4. Verified a single device listed with 25 entities as expected

Oh well, back to the drawing board. Thanks for the extra help.

**Comment by JackJPowell** [comment]
Closing stale issue. Please open a new one if any problems still exist.
