### ISSUE TITLE
Unknown Issue

### ISSUE THREAD

**Issue by TrialMaster** [JackJPowell/hass-unfoldedcircle#56]
I have been using your HA Integration for quite sometime without issue. Just recently it was not connecting to remote so i reconfigured the Integration and it asked for PIN. When I enter correct PIN it says Unknown Error. I have tried uninstalling the Integration and HAC’s components without success. Any guidance appreciated. 

Running latest version of your Integration and latest HA.

**Comment by JackJPowell** [comment]
I released a beta of v0.12 that hopefully fixes that problem. You can enable beta releases in the hacs integration and then you should see the update. Would you mind giving it a try and letting me know?

**Comment by TrialMaster** [comment]
Hi Jack. Thanks mate, that solved the issue 😀

**Comment by churchofnoise** [comment]
Seems this issue turned up again - at least for me (the 0.12 beta solved the issue but it is back)
